from manim import *
from manim_slides import *

class RSA_Presentation(Slide):
    def construct(self):
        openingPlaceholder = Text("פתיחה")
        self.play(Write(openingPlaceholder))
        self.next_slide()
        self.play(Unwrite(openingPlaceholder))
        title1 = Text("למה צריך הצפנה?")
        self.play(Write(title1))
        self.next_slide()
        title2 = title1.copy().move_to(UP * 3).scale(0.7)
        self.play(Transform(title1, title2))
        self.next_slide()
        aliceCircle = Circle(1.0, color = BLUE)
        bobCircle = Circle(1.0, color = GREEN)
        aliceCircle.move_to(LEFT * 4 + DOWN * 2)
        bobCircle.move_to(RIGHT * 4 + DOWN * 2)
        aliceText = Text("אוריאל ").scale(0.5)
        bobText = Text("איתן       ").scale(0.5)
        self.play(Create(aliceCircle))
        aliceText.next_to(aliceCircle, DOWN)
        self.play(Write(aliceText))
        self.play(Create(bobCircle))
        bobText.next_to(bobCircle, DOWN)
        self.play(Write(bobText))
        self.next_slide()
        arrow = Arrow(aliceCircle.get_end(), bobCircle.get_left())
        self.play(Create(arrow))
        self.next_slide()
        item = Text("שליפים למבחן").scale(0.7)
        box = Square(side_length=0.5, fill_color=WHITE).move_to(arrow.get_start() + UP * 0.5+ RIGHT * 0.25)
        item.move_to(arrow.get_start() + UP * 0.5 + RIGHT * 0.25)
        self.play(Write(item))
        self.play(Wait(0.5))
        self.play(Transform(item, box))
        self.next_slide()
        item2 = item.copy().move_to(arrow.get_end() + UP * 0.5 + LEFT)
        self.play(Transform(item, item2))
        self.next_slide()
        self.play(Unwrite(item))
        eib = Circle(1.0, color= RED).move_to(UP*1.5)
        arrow1 = Arrow(aliceCircle.get_end(), eib.get_left())
        arrow2 = Arrow(eib.get_right(), bobCircle.get_left())
        arrows = VGroup(arrow1, arrow2)
        self.play(Transform(arrow, arrows))
        self.next_slide()
        self.play(Create(eib))
        self.next_slide()
        eib_text = Text("הרב דוד").scale(0.5).next_to(eib, DOWN)
        self.play(Write(eib_text))
        self.next_slide()
        box = Square(side_length=0.5, fill_color=WHITE).move_to(arrow1.get_start() + UP * 0.5)
        self.play(Create(box))
        box2 = box.copy().move_to(arrow1.get_end() + UP * 0.5)
        self.play(Transform(box, box2))
        box3 = box.copy().move_to(arrow2.get_start() + UP * 0.5)
        self.play(Transform(box, box3))
        box4 = box.copy().move_to(arrow2.get_end() + UP * 0.5)
        self.play(Transform(box, box4))
        self.play(Uncreate(box))
        self.next_slide()